version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - client
    restart: always
    build: 
      dockerfile: Dockerfile.prod
      context: ./nginx
    ports:
      - '80:80'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.prod
      context: ./client